apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      version: 5.4.0
  interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # https://github.com/minio/minio/blob/master/helm/minio/values.yaml
  values:
    mode: standalone
    rootUser: morbic
    mountPath: /data
    deploymentUpdate:
      type: Recreate
    persistence:
      enabled: true
      storageClass: proxmox-data-hdd
      size: 2Ti
    ingress:
      enabled: true
      hosts:
        - s3.kmi.morbic.net
      annotations:
        cert-manager.io/cluster-issuer: cloudflare
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls:
        - hosts:
            - "s3.kmi.morbic.net"
          secretName: s3-kmi-morbic-net
    consoleIngress:
      enabled: true
      hosts:
        - console.s3.kmi.morbic.net
      annotations:
        cert-manager.io/cluster-issuer: cloudflare
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls:
        - hosts:
            - "console.s3.kmi.morbic.net"
          secretName: console-s3-kmi-morbic-net
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 2Gi
    policies:
      - name: nextcloud_rw
        statements:
          - effect: Allow
            resources:
              - 'arn:aws:s3:::nextcloud/*'
              - 'arn:aws:s3:::nextcloud'
            actions:
              - "s3:*"
      - name: photos_rw
        statements:
          - effect: Allow
            resources:
              - 'arn:aws:s3:::photos/*'
              - 'arn:aws:s3:::photos'
            actions:
              - "s3:*"
      - name: photos_s_rw
        statements:
          - effect: Allow
            resources:
              - 'arn:aws:s3:::photos-s/*'
              - 'arn:aws:s3:::photos-s'
            actions:
              - "s3:*"
    users:
      - accessKey: nextcloud
        existingSecret: minio-users
        existingSecretKey: nextcloudSecretKey
        policy: nextcloud_rw
      - accessKey: photos
        existingSecret: minio-users
        existingSecretKey: photosSecretKey
        policy: photos_rw
      - accessKey: photos-s
        existingSecret: minio-users
        existingSecretKey: sPhotosSecretKey
        policy: photos_s_rw
    buckets:
      - name: nextcloud
        policy: none
        purge: false
        versioning: true
        objectlocking: false
      - name: photos
        policy: none
        purge: false
        versioning: true
        objectlocking: false
      - name: photos-s
        policy: none
        purge: false
        versioning: true
        objectlocking: false
