apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare
  namespace: http
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kontakt@browarski.com
    privateKeySecretRef:
      name: cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare
              key: api-token
