---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./cert-issuer-letsencrypt-cloudflare.yaml
  - ./cert-browarski-com.yaml
  - ./cert-morbic-net.yaml
  # Flux-Kustomizations
  - ./traefik/ks.yaml
