apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-s3
  namespace: csi-s3
spec:
  chart:
    spec:
      chart: csi-s3
      sourceRef:
        kind: HelmRepository
        name: yandex-s3
        namespace: flux-system
      version: 0.43.0
  interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # https://github.com/yandex-cloud/k8s-csi-s3/blob/master/deploy/helm/csi-s3/values.yaml
  values:
    storageClass:
      mountOptions: "--no-systemd --memory-limit 1000 --dir-mode 0777 --file-mode 0666"
      reclaimPolicy: Retain
