---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-s3
  namespace: csi-s3
spec:
  path: ./kubernetes/apps/csi-s3/csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: px-kaas
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: csi-s3
      namespace: csi-s3
  interval: 5m
  retryInterval: 1m
  timeout: 5m
