apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-browarski-com
spec:
  secretName: wildcard-browarski-com-tls
  dnsNames:
    - "browarski.com"
    - "*.browarski.com"
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
