apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: pliki
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: flux-system
      version: 16.3.5
  interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  values:
    primary:
      persistence:
        volumeName: postgresql-data
        storageClass: proxmox-data-nvme
        size: 2Gi
