apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: pliki
spec:
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      version: 6.6.10
  interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  values:
    image:
      tag: 31.0.5-fpm
    nginx:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cloudflare
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls:
        - hosts:
            - "pliki.browarski.com"
          secretName: pliki-browarski-com
    livenessProbe:
      periodSeconds: 30
      timeoutSeconds: 30
    readinessProbe:
      periodSeconds: 30
      timeoutSeconds: 30
    phpClientHttpsFix:
      enabled: true
      protocol: https
    persistence:
      enabled: true
      storageClass: proxmox-data-hdd
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1536Mi
    nextcloud:
      host: pliki.browarski.com
      existingSecret:
        enabled: true
        secretName: nextcloud-password
        usernameKey: username
        passwordKey: password
        tokenKey: metricsToken
      phpConfigs:
        zz-config.ini: |-
          max_input_vars=5000
          max_chunk_size=100M
          upload_max_filesize=5G
          memory_limit=1024M
      objectStore:
        s3:
          enabled: true
          host: minio.minio
          ssl: false
          port: 9000
          region: kmi
          bucket: nextcloud
          autoCreate: false
          usePathStyle: true
          existingSecret: nextcloud-password
          secretKeys:
            accessKey: s3AccessKey
            secretKey: s3SecretKey
    cronjob:
      enabled: true
    internalDatabase:
      enabled: false
    redis:
      enabled: true
      global:
        storageClass: proxmox-data-nvme
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: postgresql-password
        usernameKey: user
        passwordKey: userPassword
        databaseKey: database
        hostKey: host
